version: '3.8'
services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=launchpad_indexer
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: bitnami/redis:latest
    container_name: redis_db
    restart: always
    environment:
      - REDIS_PASSWORD=password
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379
    volumes:
      - redis:/bitnami/redis/data
volumes:
  postgres:
    name: postgres-db
  redis:
    name: redis-db
