version: '3'
services:
  indexer:
    image: code4futu/starkfinance-launchpad-api:launchpad-v0.0.12
    ports:
      - '3200:3000'
    restart: always
    depends_on:
      - postgres
      - indexer-migration
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      POSTGRES_HOST: postgres_db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: exYRir5HJrLxVx5SnL7XoztzC6rJ
      POSTGRES_DB: launchpad_db
      POSTGRES_SSL: false
      STARKNET_RPC: https://starknet-testnet.public.blastapi.io,https://rpc.starknet-testnet.lava.build
      OPERATOR_PRIV_KEY: 0x038807ce99a3f5bd6ecb0e1d90d1e63eb85bbbfb689afe460d23315fe22fe470
      STARKNET_INDEX_BLOCK: 938800
      STARKNET_ACCOUNT_ADDRESS: 0x02300fC66a817547f90A96Bf45A6029033C67392F513BC8e7e05aDe0e92A36b8
      LAUNCHPAD_CLASS_HASH: 0x3a0a41f8c61a8ae4e808150e322cc06877693411d72c0e073193315ede8b40a
      AIRDROP_CLASS_HASH: 0x7093a1f43e00eeaf8bc9f42c10be68bc869d94857701f0437e42553d7dac32a
      LOCKING_ADDRESS: 0x77ef4b9951417dc2886d33b96cf9f04b3bea4ecb2b06da2177902964aaef0cf
      NFT_ADDRESS: 0x19311b73b5e1fd854853e759883af4a72c702986c08806622c6fad47c2853e1
    logging:
      driver: 'json-file'
      options:
        max-file: '5' # number of files or file count
        max-size: '10m' # file size

  indexer-migration:
    image: code4futu/starkfinance-launchpad-api:launchpad-v0.0.12
    depends_on:
      - postgres
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      POSTGRES_HOST: postgres_db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: exYRir5HJrLxVx5SnL7XoztzC6rJ
      POSTGRES_DB: launchpad_db
      POSTGRES_SSL: false
    command: 'npm run migration:api:run'
    logging:
      driver: 'json-file'
      options:
        max-file: '5' # number of files or file count
        max-size: '10m' # file size

  postgres:
    image: postgres:14
    container_name: postgres_db
    ports:
      - '5432:5432'
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: exYRir5HJrLxVx5SnL7XoztzC6rJ
      POSTGRES_DB: indexer-db
      # FIXME: remove this env. var. which we shouldn't need. Introduced by
      # <https://github.com/graphprotocol/graph-node/pull/3511>, maybe as a
      # workaround for https://github.com/docker/for-mac/issues/6270?
      PGDATA: '/var/lib/postgresql/data'
      # POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    logging:
      driver: 'json-file'
      options:
        max-file: '5' # number of files or file count
        max-size: '10m' # file size

