import { appConfig } from './app.config';
const sample = require('lodash/sample');

export const INDEXER_QUEUE_NAME = 'POLYSPORT_INDEXER_QUEUE';
export const INDEXER_PROCESS_NAME = 'POLYSPORT_INDEXER_PROCESS';

export const randomRPC = (): string => sample(appConfig.rpc.split(','));

export const DEFAULT_BLOCK_NUMBER = 47320848;
export const CHUNK_BLOCK_NUMBER = 1000;

export enum EWin {
  LOSE,
  WIN,
  JACKPOT,
}

export const TOPIC0 = {
  mint: '0x3a8a89b59a31c39a36febecb987e0657ab7b7c73b60ebacb44dcb9886c2d5c8a',
  burn: '0xd6a6bcd88cdc4656d5f4e14e7dfbc9bc3f2f9811f8d6b508f3bee7d999d4d41c',
  transfer:
    '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef',
};

export const ID_ATTRIBUTE_MAPPING = {
  1: [
    { trait_type: 'Stars', value: '5' },
    { trait_type: 'Color', value: 'Gold' },
    { trait_type: 'Position', value: 'CF' },
    { trait_type: 'Country', value: 'France' },
    { trait_type: 'Market Value', value: '$180M' },
  ],
  2: [
    { trait_type: 'Stars', value: '5' },
    { trait_type: 'Color', value: 'Gold' },
    { trait_type: 'Position', value: 'CF' },
    { trait_type: 'Country', value: 'Norway' },
    { trait_type: 'Market Value', value: '$170M' },
  ],
  3: [
    { trait_type: 'Stars', value: '5' },
    { trait_type: 'Color', value: 'Gold' },
    { trait_type: 'Position', value: 'LW' },
    { trait_type: 'Country', value: 'Brazil' },
    { trait_type: 'Market Value', value: '$120M' },
  ],
  4: [
    { trait_type: 'Stars', value: '5' },
    { trait_type: 'Color', value: 'Gold' },
    { trait_type: 'Position', value: 'CM' },
    { trait_type: 'Country', value: 'England' },
    { trait_type: 'Market Value', value: '$120M' },
  ],
  5: [
    { trait_type: 'Stars', value: '5' },
    { trait_type: 'Color', value: 'Gold' },
    { trait_type: 'Position', value: 'RW' },
    { trait_type: 'Country', value: 'Nigeria' },
    { trait_type: 'Market Value', value: '$110M' },
  ],
  6: [
    { trait_type: 'Stars', value: '5' },
    { trait_type: 'Color', value: 'Gold' },
    { trait_type: 'Position', value: 'AM' },
    { trait_type: 'Country', value: 'Germany' },
    { trait_type: 'Market Value', value: '$110M' },
  ],
  7: [
    { trait_type: 'Stars', value: '5' },
    { trait_type: 'Color', value: 'Gold' },
    { trait_type: 'Position', value: 'LW' },
    { trait_type: 'Country', value: 'England' },
    { trait_type: 'Market Value', value: '$110M' },
  ],
  8: [
    { trait_type: 'Stars', value: '5' },
    { trait_type: 'Color', value: 'Gold' },
    { trait_type: 'Position', value: 'CM' },
    { trait_type: 'Country', value: 'Spain' },
    { trait_type: 'Market Value', value: '$100M' },
  ],
  9: [
    { trait_type: 'Stars', value: '5' },
    { trait_type: 'Color', value: 'Gold' },
    { trait_type: 'Position', value: 'CF' },
    { trait_type: 'Country', value: 'Nigeria' },
    { trait_type: 'Market Value', value: '$100M' },
  ],
  10: [
    { trait_type: 'Stars', value: '5' },
    { trait_type: 'Color', value: 'Gold' },
    { trait_type: 'Position', value: 'CM' },
    { trait_type: 'Country', value: 'Spain' },
    { trait_type: 'Market Value', value: '$100M' },
  ],
  11: [
    { trait_type: 'Stars', value: '4' },
    { trait_type: 'Color', value: 'Ruby' },
    { trait_type: 'Position', value: 'CM' },
    { trait_type: 'Country', value: 'Spain' },
    { trait_type: 'Market Value', value: '$90M' },
  ],
  12: [
    { trait_type: 'Stars', value: '4' },
    { trait_type: 'Color', value: 'Ruby' },
    { trait_type: 'Position', value: 'DM' },
    { trait_type: 'Country', value: 'France' },
    { trait_type: 'Market Value', value: '$90M' },
  ],
  13: [
    { trait_type: 'Stars', value: '4' },
    { trait_type: 'Color', value: 'Ruby' },
    { trait_type: 'Position', value: 'CF' },
    { trait_type: 'Country', value: 'England' },
    { trait_type: 'Market Value', value: '$90M' },
  ],
  14: [
    { trait_type: 'Stars', value: '4' },
    { trait_type: 'Color', value: 'Ruby' },
    { trait_type: 'Position', value: 'DM' },
    { trait_type: 'Country', value: 'Argentina' },
    { trait_type: 'Market Value', value: '$85M' },
  ],
  15: [
    { trait_type: 'Stars', value: '4' },
    { trait_type: 'Color', value: 'Ruby' },
    { trait_type: 'Position', value: 'AM' },
    { trait_type: 'Country', value: 'Germany' },
    { trait_type: 'Market Value', value: '$85M' },
  ],
  16: [
    { trait_type: 'Stars', value: '4' },
    { trait_type: 'Color', value: 'Ruby' },
    { trait_type: 'Position', value: 'LM' },
    { trait_type: 'Country', value: 'Georgia' },
    { trait_type: 'Market Value', value: '$85M' },
  ],
  17: [
    { trait_type: 'Stars', value: '4' },
    { trait_type: 'Color', value: 'Ruby' },
    { trait_type: 'Position', value: 'RW' },
    { trait_type: 'Country', value: 'Spain' },
    { trait_type: 'Market Value', value: '$80M' },
  ],
  18: [
    { trait_type: 'Stars', value: '4' },
    { trait_type: 'Color', value: 'Ruby' },
    { trait_type: 'Position', value: 'CF' },
    { trait_type: 'Country', value: 'Argentina' },
    { trait_type: 'Market Value', value: '$80M' },
  ],
  19: [
    { trait_type: 'Stars', value: '4' },
    { trait_type: 'Color', value: 'Ruby' },
    { trait_type: 'Position', value: 'DM' },
    { trait_type: 'Country', value: 'England' },
    { trait_type: 'Market Value', value: '$80M' },
  ],
  20: [
    { trait_type: 'Stars', value: '4' },
    { trait_type: 'Color', value: 'Ruby' },
    { trait_type: 'Position', value: 'RM' },
    { trait_type: 'Country', value: 'Brazil' },
    { trait_type: 'Market Value', value: '$80M' },
  ],
  21: [
    { trait_type: 'Stars', value: '3' },
    { trait_type: 'Color', value: 'Amethyst' },
    { trait_type: 'Position', value: 'ST' },
    { trait_type: 'Country', value: 'Portugal' },
    { trait_type: 'Market Value', value: '$80M' },
  ],
  22: [
    { trait_type: 'Stars', value: '3' },
    { trait_type: 'Color', value: 'Amethyst' },
    { trait_type: 'Position', value: 'SS' },
    { trait_type: 'Country', value: 'France' },
    { trait_type: 'Market Value', value: '$80M' },
  ],
  23: [
    { trait_type: 'Stars', value: '3' },
    { trait_type: 'Color', value: 'Amethyst' },
    { trait_type: 'Position', value: 'AM' },
    { trait_type: 'Country', value: 'Norway' },
    { trait_type: 'Market Value', value: '$80M' },
  ],
  24: [
    { trait_type: 'Stars', value: '3' },
    { trait_type: 'Color', value: 'Amethyst' },
    { trait_type: 'Position', value: 'LM' },
    { trait_type: 'Country', value: 'England' },
    { trait_type: 'Market Value', value: '$80M' },
  ],
  25: [
    { trait_type: 'Stars', value: '3' },
    { trait_type: 'Color', value: 'Amethyst' },
    { trait_type: 'Position', value: 'AM' },
    { trait_type: 'Country', value: 'Portugal' },
    { trait_type: 'Market Value', value: '$80M' },
  ],
  26: [
    { trait_type: 'Stars', value: '3' },
    { trait_type: 'Color', value: 'Amethyst' },
    { trait_type: 'Position', value: 'DM' },
    { trait_type: 'Country', value: 'Germany' },
    { trait_type: 'Market Value', value: '$80M' },
  ],
  27: [
    { trait_type: 'Stars', value: '3' },
    { trait_type: 'Color', value: 'Amethyst' },
    { trait_type: 'Position', value: 'AM' },
    { trait_type: 'Country', value: 'Belgium' },
    { trait_type: 'Market Value', value: '$80M' },
  ],
  28: [
    { trait_type: 'Stars', value: '3' },
    { trait_type: 'Color', value: 'Amethyst' },
    { trait_type: 'Position', value: 'LW' },
    { trait_type: 'Country', value: 'Colombia' },
    { trait_type: 'Market Value', value: '$75M' },
  ],
  29: [
    { trait_type: 'Stars', value: '3' },
    { trait_type: 'Color', value: 'Amethyst' },
    { trait_type: 'Position', value: 'CB' },
    { trait_type: 'Country', value: 'Croatia' },
    { trait_type: 'Market Value', value: '$75M' },
  ],
  30: [
    { trait_type: 'Stars', value: '3' },
    { trait_type: 'Color', value: 'Amethyst' },
    { trait_type: 'Position', value: 'CF' },
    { trait_type: 'Country', value: 'Brazil' },
    { trait_type: 'Market Value', value: '$75M' },
  ],
  31: [
    { trait_type: 'Stars', value: '2' },
    { trait_type: 'Color', value: 'Emerald' },
    { trait_type: 'Position', value: 'CB' },
    { trait_type: 'Country', value: 'Netherlands' },
    { trait_type: 'Market Value', value: '$75M' },
  ],
  32: [
    { trait_type: 'Stars', value: '2' },
    { trait_type: 'Color', value: 'Emerald' },
    { trait_type: 'Position', value: 'CF' },
    { trait_type: 'Country', value: 'Serbia' },
    { trait_type: 'Market Value', value: '$75M' },
  ],
  33: [
    { trait_type: 'Stars', value: '2' },
    { trait_type: 'Color', value: 'Emerald' },
    { trait_type: 'Position', value: 'CB' },
    { trait_type: 'Country', value: 'Portugal' },
    { trait_type: 'Market Value', value: '$75M' },
  ],
  34: [
    { trait_type: 'Stars', value: '2' },
    { trait_type: 'Color', value: 'Emerald' },
    { trait_type: 'Position', value: 'AM' },
    { trait_type: 'Country', value: 'Portugal' },
    { trait_type: 'Market Value', value: '$75M' },
  ],
  35: [
    { trait_type: 'Stars', value: '2' },
    { trait_type: 'Color', value: 'Emerald' },
    { trait_type: 'Position', value: 'LW' },
    { trait_type: 'Country', value: 'Brazil' },
    { trait_type: 'Market Value', value: '$70M' },
  ],
  36: [
    { trait_type: 'Stars', value: '2' },
    { trait_type: 'Color', value: 'Emerald' },
    { trait_type: 'Position', value: 'RW' },
    { trait_type: 'Country', value: 'Brazil' },
    { trait_type: 'Market Value', value: '$75M' },
  ],
  37: [
    { trait_type: 'Stars', value: '2' },
    { trait_type: 'Color', value: 'Emerald' },
    { trait_type: 'Position', value: 'CF' },
    { trait_type: 'Country', value: 'Uruguay' },
    { trait_type: 'Market Value', value: '$70M' },
  ],
  38: [
    { trait_type: 'Stars', value: '2' },
    { trait_type: 'Color', value: 'Emerald' },
    { trait_type: 'Position', value: 'CB' },
    { trait_type: 'Country', value: 'Uruguay' },
    { trait_type: 'Market Value', value: '$70M' },
  ],
  39: [
    { trait_type: 'Stars', value: '2' },
    { trait_type: 'Color', value: 'Emerald' },
    { trait_type: 'Position', value: 'RB' },
    { trait_type: 'Country', value: 'England' },
    { trait_type: 'Market Value', value: '$70M' },
  ],
  40: [
    { trait_type: 'Stars', value: '2' },
    { trait_type: 'Color', value: 'Emerald' },
    { trait_type: 'Position', value: 'LB' },
    { trait_type: 'Country', value: 'Canada' },
    { trait_type: 'Market Value', value: '$70M' },
  ],
  41: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CB' },
    { trait_type: 'Country', value: 'Brazil' },
    { trait_type: 'Market Value', value: '$70M' },
  ],
  42: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'RB' },
    { trait_type: 'Country', value: 'Morocco' },
    { trait_type: 'Market Value', value: '$70M' },
  ],
  43: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CM' },
    { trait_type: 'Country', value: 'Italy' },
    { trait_type: 'Market Value', value: '$70M' },
  ],
  44: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'LW' },
    { trait_type: 'Country', value: 'England' },
    { trait_type: 'Market Value', value: '$70M' },
  ],
  45: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'RW' },
    { trait_type: 'Country', value: 'Germany' },
    { trait_type: 'Market Value', value: '$70M' },
  ],
  46: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CB' },
    { trait_type: 'Country', value: 'Brazil' },
    { trait_type: 'Market Value', value: '$70M' },
  ],
  47: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'RW' },
    { trait_type: 'Country', value: 'Egypt' },
    { trait_type: 'Market Value', value: '$70M' },
  ],
  48: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'LW' },
    { trait_type: 'Country', value: 'Brazil' },
    { trait_type: 'Market Value', value: '$70M' },
  ],
  49: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'LW' },
    { trait_type: 'Country', value: 'Portugal' },
    { trait_type: 'Market Value', value: '$65M' },
  ],
  50: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CF' },
    { trait_type: 'Country', value: 'France' },
    { trait_type: 'Market Value', value: '$65M' },
  ],
  51: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CB' },
    { trait_type: 'Country', value: 'France' },
    { trait_type: 'Market Value', value: '$65M' },
  ],
  52: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'AM' },
    { trait_type: 'Country', value: 'England' },
    { trait_type: 'Market Value', value: '$65M' },
  ],
  53: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'RB' },
    { trait_type: 'Country', value: 'England' },
    { trait_type: 'Market Value', value: '$65M' },
  ],
  54: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'LF' },
    { trait_type: 'Country', value: 'France' },
    { trait_type: 'Market Value', value: '$65M' },
  ],
  55: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CM' },
    { trait_type: 'Country', value: 'Germany' },
    { trait_type: 'Market Value', value: '$65M' },
  ],
  56: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CM' },
    { trait_type: 'Country', value: 'Colombia' },
    { trait_type: 'Market Value', value: '$60M' },
  ],
  57: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'LW' },
    { trait_type: 'Country', value: 'Ukraine' },
    { trait_type: 'Market Value', value: '$60M' },
  ],
  58: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CF' },
    { trait_type: 'Country', value: 'Canada' },
    { trait_type: 'Market Value', value: '$60M' },
  ],
  59: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'DM' },
    { trait_type: 'Country', value: 'Brazil' },
    { trait_type: 'Market Value', value: '$60M' },
  ],
  60: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'LW' },
    { trait_type: 'Country', value: 'Netherlands' },
    { trait_type: 'Market Value', value: '$60M' },
  ],
  61: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CB' },
    { trait_type: 'Country', value: 'Netherlands' },
    { trait_type: 'Market Value', value: '$60M' },
  ],
  62: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CB' },
    { trait_type: 'Country', value: 'Argentina' },
    { trait_type: 'Market Value', value: '$60M' },
  ],
  63: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CB' },
    { trait_type: 'Country', value: 'France' },
    { trait_type: 'Market Value', value: '$60M' },
  ],
  64: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'LB' },
    { trait_type: 'Country', value: 'France' },
    { trait_type: 'Market Value', value: '$60M' },
  ],
  65: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CM' },
    { trait_type: 'Country', value: 'Netherlands' },
    { trait_type: 'Market Value', value: '$60M' },
  ],
  66: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'AM' },
    { trait_type: 'Country', value: 'Germany' },
    { trait_type: 'Market Value', value: '$60M' },
  ],
  67: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'RM' },
    { trait_type: 'Country', value: 'France' },
    { trait_type: 'Market Value', value: '$60M' },
  ],
  68: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CM' },
    { trait_type: 'Country', value: 'Serbia' },
    { trait_type: 'Market Value', value: '$60M' },
  ],
  69: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CB' },
    { trait_type: 'Country', value: 'Slovakia' },
    { trait_type: 'Market Value', value: '$60M' },
  ],
  70: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CB' },
    { trait_type: 'Country', value: 'Portugal' },
    { trait_type: 'Market Value', value: '$60M' },
  ],
  71: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'LW' },
    { trait_type: 'Country', value: 'England' },
    { trait_type: 'Market Value', value: '$60M' },
  ],
  72: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'GK' },
    { trait_type: 'Country', value: 'Belgium' },
    { trait_type: 'Market Value', value: '$60M' },
  ],
  73: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'LW' },
    { trait_type: 'Country', value: 'South Korea' },
    { trait_type: 'Market Value', value: '$60M' },
  ],
  74: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'DM' },
    { trait_type: 'Country', value: 'Ecuador' },
    { trait_type: 'Market Value', value: '$55M' },
  ],
  75: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CB' },
    { trait_type: 'Country', value: 'France' },
    { trait_type: 'Market Value', value: '$55M' },
  ],
  76: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'RW' },
    { trait_type: 'Country', value: 'Sweden' },
    { trait_type: 'Market Value', value: '$55M' },
  ],
  77: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'LW' },
    { trait_type: 'Country', value: 'England' },
    { trait_type: 'Market Value', value: '$55M' },
  ],
  78: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CF' },
    { trait_type: 'Country', value: 'Brazil' },
    { trait_type: 'Market Value', value: '$55M' },
  ],
  79: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'LW' },
    { trait_type: 'Country', value: 'Portugal' },
    { trait_type: 'Market Value', value: '$55M' },
  ],
  80: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CB' },
    { trait_type: 'Country', value: 'Italy' },
    { trait_type: 'Market Value', value: '$55M' },
  ],
  81: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'AM' },
    { trait_type: 'Country', value: 'England' },
    { trait_type: 'Market Value', value: '$55M' },
  ],
  82: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'RW' },
    { trait_type: 'Country', value: 'Germany' },
    { trait_type: 'Market Value', value: '$55M' },
  ],
  83: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CF' },
    { trait_type: 'Country', value: 'Argentina' },
    { trait_type: 'Market Value', value: '$55M' },
  ],
  84: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CB' },
    { trait_type: 'Country', value: 'South Korea' },
    { trait_type: 'Market Value', value: '$55M' },
  ],
  85: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CB' },
    { trait_type: 'Country', value: 'Argentina' },
    { trait_type: 'Market Value', value: '$55M' },
  ],
  86: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'SS' },
    { trait_type: 'Country', value: 'Portugal' },
    { trait_type: 'Market Value', value: '$55M' },
  ],
  87: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CB' },
    { trait_type: 'Country', value: 'Brazil' },
    { trait_type: 'Market Value', value: '$55M' },
  ],
  88: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'RW' },
    { trait_type: 'Country', value: 'Brazil' },
    { trait_type: 'Market Value', value: '$55M' },
  ],
  89: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'DM' },
    { trait_type: 'Country', value: 'Italy' },
    { trait_type: 'Market Value', value: '$55M' },
  ],
  90: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'LW' },
    { trait_type: 'Country', value: 'France' },
    { trait_type: 'Market Value', value: '$55M' },
  ],
  91: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'LW' },
    { trait_type: 'Country', value: 'Spain' },
    { trait_type: 'Market Value', value: '$55M' },
  ],
  92: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CF' },
    { trait_type: 'Country', value: 'Sweden' },
    { trait_type: 'Market Value', value: '$55M' },
  ],
  93: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'LW' },
    { trait_type: 'Country', value: 'Italy' },
    { trait_type: 'Market Value', value: '$50M' },
  ],
  94: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CM' },
    { trait_type: 'Country', value: 'Spain' },
    { trait_type: 'Market Value', value: '$50M' },
  ],
  95: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'RB' },
    { trait_type: 'Country', value: 'England' },
    { trait_type: 'Market Value', value: '$50M' },
  ],
  96: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'GK' },
    { trait_type: 'Country', value: 'Italy' },
    { trait_type: 'Market Value', value: '$50M' },
  ],
  97: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CB' },
    { trait_type: 'Country', value: 'France' },
    { trait_type: 'Market Value', value: '$50M' },
  ],
  98: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CF' },
    { trait_type: 'Country', value: 'England' },
    { trait_type: 'Market Value', value: '$50M' },
  ],
  99: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CM' },
    { trait_type: 'Country', value: 'Italy' },
    { trait_type: 'Market Value', value: '$50M' },
  ],
  100: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'LB' },
    { trait_type: 'Country', value: 'England' },
    { trait_type: 'Market Value', value: '$50M' },
  ],
  101: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CM' },
    { trait_type: 'Country', value: 'Portugal' },
    { trait_type: 'Market Value', value: '$50M' },
  ],
  102: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'AM' },
    { trait_type: 'Country', value: 'Brazil' },
    { trait_type: 'Market Value', value: '$45M' },
  ],
  103: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CB' },
    { trait_type: 'Country', value: 'Spain' },
    { trait_type: 'Market Value', value: '$45M' },
  ],
  104: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CB' },
    { trait_type: 'Country', value: 'Netherlands' },
    { trait_type: 'Market Value', value: '$45M' },
  ],
  105: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'GK' },
    { trait_type: 'Country', value: 'Portugal' },
    { trait_type: 'Market Value', value: '$45M' },
  ],
  106: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CF' },
    { trait_type: 'Country', value: 'England' },
    { trait_type: 'Market Value', value: '$40M' },
  ],
  107: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CB' },
    { trait_type: 'Country', value: 'England' },
    { trait_type: 'Market Value', value: '$40M' },
  ],
  108: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'GK' },
    { trait_type: 'Country', value: 'Brazil' },
    { trait_type: 'Market Value', value: '$40M' },
  ],
  109: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'GK' },
    { trait_type: 'Country', value: 'Brazil' },
    { trait_type: 'Market Value', value: '$40M' },
  ],
  110: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'LW' },
    { trait_type: 'Country', value: 'Senegal' },
    { trait_type: 'Market Value', value: '$35M' },
  ],
  111: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CM' },
    { trait_type: 'Country', value: 'Denmark' },
    { trait_type: 'Market Value', value: '$40M' },
  ],
  112: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CB' },
    { trait_type: 'Country', value: 'Netherlands' },
    { trait_type: 'Market Value', value: '$40M' },
  ],
  113: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'GK' },
    { trait_type: 'Country', value: 'Belgium' },
    { trait_type: 'Market Value', value: '$40M' },
  ],
  114: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'GK' },
    { trait_type: 'Country', value: 'Brazil' },
    { trait_type: 'Market Value', value: '$40M' },
  ],
  115: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'RW' },
    { trait_type: 'Country', value: 'Argentina' },
    { trait_type: 'Market Value', value: '$40M' },
  ],
  116: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CM' },
    { trait_type: 'Country', value: 'Argentina' },
    { trait_type: 'Market Value', value: '$40M' },
  ],
  117: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CM' },
    { trait_type: 'Country', value: 'Portugal' },
    { trait_type: 'Market Value', value: '$40M' },
  ],
  118: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'DM' },
    { trait_type: 'Country', value: 'Belgium' },
    { trait_type: 'Market Value', value: '$40M' },
  ],
  119: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CB' },
    { trait_type: 'Country', value: 'Netherlands' },
    { trait_type: 'Market Value', value: '$40M' },
  ],
  120: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'RW' },
    { trait_type: 'Country', value: 'Spain' },
    { trait_type: 'Market Value', value: '$40M' },
  ],
  121: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CF' },
    { trait_type: 'Country', value: 'Portugal' },
    { trait_type: 'Market Value', value: '$40M' },
  ],
  122: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CB' },
    { trait_type: 'Country', value: 'Brazil' },
    { trait_type: 'Market Value', value: '$40M' },
  ],
  123: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'LW' },
    { trait_type: 'Country', value: 'England' },
    { trait_type: 'Market Value', value: '$40M' },
  ],
  124: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CB' },
    { trait_type: 'Country', value: 'France' },
    { trait_type: 'Market Value', value: '$40M' },
  ],
  125: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'AM' },
    { trait_type: 'Country', value: 'Hungary' },
    { trait_type: 'Market Value', value: '$40M' },
  ],
  126: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'DM' },
    { trait_type: 'Country', value: 'Spain' },
    { trait_type: 'Market Value', value: '$40M' },
  ],
  127: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CB' },
    { trait_type: 'Country', value: 'Germany' },
    { trait_type: 'Market Value', value: '$40M' },
  ],
  128: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CM' },
    { trait_type: 'Country', value: 'Uruguay' },
    { trait_type: 'Market Value', value: '$40M' },
  ],
  129: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CM' },
    { trait_type: 'Country', value: 'Senegal' },
    { trait_type: 'Market Value', value: '$40M' },
  ],
  130: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'DM' },
    { trait_type: 'Country', value: 'Algeria' },
    { trait_type: 'Market Value', value: '$40M' },
  ],
  131: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'LW' },
    { trait_type: 'Country', value: 'Spain' },
    { trait_type: 'Market Value', value: '$40M' },
  ],
  132: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'AM' },
    { trait_type: 'Country', value: 'Spain' },
    { trait_type: 'Market Value', value: '$40M' },
  ],
  133: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'LB' },
    { trait_type: 'Country', value: 'Spain' },
    { trait_type: 'Market Value', value: '$40M' },
  ],
  134: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CM' },
    { trait_type: 'Country', value: 'Argentina' },
    { trait_type: 'Market Value', value: '$40M' },
  ],
  135: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'DM' },
    { trait_type: 'Country', value: 'Portugal' },
    { trait_type: 'Market Value', value: '$40M' },
  ],
  136: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'LB' },
    { trait_type: 'Country', value: 'Ukraine' },
    { trait_type: 'Market Value', value: '$40M' },
  ],
  137: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CB' },
    { trait_type: 'Country', value: 'Denmark' },
    { trait_type: 'Market Value', value: '$40M' },
  ],
  138: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'AM' },
    { trait_type: 'Country', value: 'Germany' },
    { trait_type: 'Market Value', value: '$40M' },
  ],
  139: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CM' },
    { trait_type: 'Country', value: 'Poland' },
    { trait_type: 'Market Value', value: '$40M' },
  ],
  140: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CM' },
    { trait_type: 'Country', value: 'France' },
    { trait_type: 'Market Value', value: '$35M' },
  ],
  141: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CF' },
    { trait_type: 'Country', value: 'Belgium' },
    { trait_type: 'Market Value', value: '$35M' },
  ],
  142: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CB' },
    { trait_type: 'Country', value: 'Austria' },
    { trait_type: 'Market Value', value: '$35M' },
  ],
  143: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CM' },
    { trait_type: 'Country', value: 'Croatia' },
    { trait_type: 'Market Value', value: '$35M' },
  ],
  144: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'GK' },
    { trait_type: 'Country', value: 'England' },
    { trait_type: 'Market Value', value: '$35M' },
  ],
  145: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'AM' },
    { trait_type: 'Country', value: 'England' },
    { trait_type: 'Market Value', value: '$35M' },
  ],
  146: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CM' },
    { trait_type: 'Country', value: 'Spain' },
    { trait_type: 'Market Value', value: '$35M' },
  ],
  147: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CM' },
    { trait_type: 'Country', value: 'Brazil' },
    { trait_type: 'Market Value', value: '$35M' },
  ],
  148: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'RW' },
    { trait_type: 'Country', value: 'England' },
    { trait_type: 'Market Value', value: '$35M' },
  ],
  149: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'DM' },
    { trait_type: 'Country', value: 'Ghana' },
    { trait_type: 'Market Value', value: '$35M' },
  ],
  150: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'DM' },
    { trait_type: 'Country', value: 'Slovakia' },
    { trait_type: 'Market Value', value: '$35M' },
  ],
  151: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CM' },
    { trait_type: 'Country', value: 'England' },
    { trait_type: 'Market Value', value: '$35M' },
  ],
  152: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CF' },
    { trait_type: 'Country', value: 'Denmark' },
    { trait_type: 'Market Value', value: '$35M' },
  ],
  153: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CB' },
    { trait_type: 'Country', value: 'France' },
    { trait_type: 'Market Value', value: '$32M' },
  ],
  154: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'AM' },
    { trait_type: 'Country', value: 'England' },
    { trait_type: 'Market Value', value: '$32M' },
  ],
  155: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'RB' },
    { trait_type: 'Country', value: 'Spain' },
    { trait_type: 'Market Value', value: '$32M' },
  ],
  156: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'LW' },
    { trait_type: 'Country', value: 'Belgium' },
    { trait_type: 'Market Value', value: '$32M' },
  ],
  157: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'RB' },
    { trait_type: 'Country', value: 'Netherlands' },
    { trait_type: 'Market Value', value: '$32M' },
  ],
  158: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'LW' },
    { trait_type: 'Country', value: 'Spain' },
    { trait_type: 'Market Value', value: '$32M' },
  ],
  159: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CM' },
    { trait_type: 'Country', value: 'Brazil' },
    { trait_type: 'Market Value', value: '$32M' },
  ],
  160: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'LW' },
    { trait_type: 'Country', value: 'France' },
    { trait_type: 'Market Value', value: '$30M' },
  ],
  161: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'RB' },
    { trait_type: 'Country', value: 'Argentina' },
    { trait_type: 'Market Value', value: '$30M' },
  ],
  162: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CF' },
    { trait_type: 'Country', value: 'France' },
    { trait_type: 'Market Value', value: '$30M' },
  ],
  163: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'SS' },
    { trait_type: 'Country', value: 'Italy' },
    { trait_type: 'Market Value', value: '$30M' },
  ],
  164: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'DM' },
    { trait_type: 'Country', value: 'Mexico' },
    { trait_type: 'Market Value', value: '$30M' },
  ],
  165: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CB' },
    { trait_type: 'Country', value: 'England' },
    { trait_type: 'Market Value', value: '$30M' },
  ],
  166: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CB' },
    { trait_type: 'Country', value: 'France' },
    { trait_type: 'Market Value', value: '$30M' },
  ],
  167: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'RB' },
    { trait_type: 'Country', value: 'Portugal' },
    { trait_type: 'Market Value', value: '$30M' },
  ],
  168: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'DM' },
    { trait_type: 'Country', value: 'Ivory Coast' },
    { trait_type: 'Market Value', value: '$30M' },
  ],
  169: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'RB' },
    { trait_type: 'Country', value: 'France' },
    { trait_type: 'Market Value', value: '$30M' },
  ],
  170: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CB' },
    { trait_type: 'Country', value: 'Spain' },
    { trait_type: 'Market Value', value: '$30M' },
  ],
  171: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'DM' },
    { trait_type: 'Country', value: 'England' },
    { trait_type: 'Market Value', value: '$30M' },
  ],
  172: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'LB' },
    { trait_type: 'Country', value: 'England' },
    { trait_type: 'Market Value', value: '$30M' },
  ],
  173: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'AM' },
    { trait_type: 'Country', value: 'Italy' },
    { trait_type: 'Market Value', value: '$30M' },
  ],
  174: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'DM' },
    { trait_type: 'Country', value: 'Czech Republic' },
    { trait_type: 'Market Value', value: '$30M' },
  ],
  175: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CM' },
    { trait_type: 'Country', value: 'Spain' },
    { trait_type: 'Market Value', value: '$30M' },
  ],
  176: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CB' },
    { trait_type: 'Country', value: 'France' },
    { trait_type: 'Market Value', value: '$30M' },
  ],
  177: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'RW' },
    { trait_type: 'Country', value: 'Paraguay' },
    { trait_type: 'Market Value', value: '$30M' },
  ],
  178: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'LW' },
    { trait_type: 'Country', value: 'France' },
    { trait_type: 'Market Value', value: '$30M' },
  ],
  179: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'GK' },
    { trait_type: 'Country', value: 'Switzerland' },
    { trait_type: 'Market Value', value: '$30M' },
  ],
  180: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'DM' },
    { trait_type: 'Country', value: 'Portugal' },
    { trait_type: 'Market Value', value: '$30M' },
  ],
  181: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CB' },
    { trait_type: 'Country', value: 'Uruguay' },
    { trait_type: 'Market Value', value: '$30M' },
  ],
  182: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'LB' },
    { trait_type: 'Country', value: 'England' },
    { trait_type: 'Market Value', value: '$30M' },
  ],
  183: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'GK' },
    { trait_type: 'Country', value: 'France' },
    { trait_type: 'Market Value', value: '$30M' },
  ],
  184: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CB' },
    { trait_type: 'Country', value: 'Netherlands' },
    { trait_type: 'Market Value', value: '$30M' },
  ],
  185: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CB' },
    { trait_type: 'Country', value: 'Belgium' },
    { trait_type: 'Market Value', value: '$30M' },
  ],
  186: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CM' },
    { trait_type: 'Country', value: 'Turkey' },
    { trait_type: 'Market Value', value: '$30M' },
  ],
  187: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'GK' },
    { trait_type: 'Country', value: 'Slovenia' },
    { trait_type: 'Market Value', value: '$30M' },
  ],
  188: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'DM' },
    { trait_type: 'Country', value: 'Italy' },
    { trait_type: 'Market Value', value: '$28M' },
  ],
  189: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'GK' },
    { trait_type: 'Country', value: 'Belgium' },
    { trait_type: 'Market Value', value: '$28M' },
  ],
  190: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CF' },
    { trait_type: 'Country', value: 'Brazil' },
    { trait_type: 'Market Value', value: '$28M' },
  ],
  191: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CM' },
    { trait_type: 'Country', value: 'England' },
    { trait_type: 'Market Value', value: '$28M' },
  ],
  192: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CM' },
    { trait_type: 'Country', value: 'England' },
    { trait_type: 'Market Value', value: '$28M' },
  ],
  193: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'RW' },
    { trait_type: 'Country', value: 'Portugal' },
    { trait_type: 'Market Value', value: '$25M' },
  ],
  194: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CM' },
    { trait_type: 'Country', value: 'France' },
    { trait_type: 'Market Value', value: '$25M' },
  ],
  195: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'GK' },
    { trait_type: 'Country', value: 'Spain' },
    { trait_type: 'Market Value', value: '$25M' },
  ],
  196: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'LW' },
    { trait_type: 'Country', value: 'England' },
    { trait_type: 'Market Value', value: '$25M' },
  ],
  197: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CF' },
    { trait_type: 'Country', value: 'England' },
    { trait_type: 'Market Value', value: '$25M' },
  ],
  198: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CF' },
    { trait_type: 'Country', value: 'France' },
    { trait_type: 'Market Value', value: '$25M' },
  ],
  199: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CM' },
    { trait_type: 'Country', value: 'Spain' },
    { trait_type: 'Market Value', value: '$25M' },
  ],
  200: [
    { trait_type: 'Stars', value: '1' },
    { trait_type: 'Color', value: 'Silver' },
    { trait_type: 'Position', value: 'CB' },
    { trait_type: 'Country', value: 'Denmark' },
    { trait_type: 'Market Value', value: '$25M' },
  ],
};

export const ID_PICTURE_MAPPING = {
  1: 'QmchCXbL64gDDfrRQeGVxj3FTDdud3NGzJL7WXuCRDLfZ2',
  2: 'QmcmHTZq1j2Lw7g8NFuYa6wPmqQAsLrLoHu51gwBeX2FpW',
  3: 'QmVjxn8CZEuJbYqABGMgD3AP8mPN6cgJZJ2JG8WrUYTJdQ',
  4: 'QmavQ7qrKiY8frUspFLoDsun6TgoFYmsFSJxu9XP54LFmJ',
  5: 'QmSRvgpTV1KVu25AHxFHW5qLfyVS7MVwSTst2frbUre4ei',
  6: 'QmQPsUN3Zb1ewfkuL9tyNrG9461H1Y2hwDEMzi4cB2cWV3',
  7: 'QmUVC6QXpvo5PD4m64eiFHTrhCcWe1D3f4yByQLGE6Wv2s',
  8: 'QmRfqobvH5b7Yymf7aKxNhVi2SycTKRtPtZU1ETYBHGhmn',
  9: 'QmQMuobcbewoJKd5dECxAFAGtAZw7CvWTnsiz8NZB4eEdP',
  10: 'Qma3aJ7NmMcd2H7WLtcD6M6Ntd6eptKJ8PWyoPCRCNRP4E',
  11: 'QmeD7SoHNQ5zq3tkRAVuaxEpL7GaVhHhiLCxFP96726udv',
  12: 'QmSFC7AfBUpgAGT8pvYwWDQkzSP734hMRg4n5GTGjiQ8Jd',
  13: 'QmTCDfKQJvmwP8Kkks3dDeD4PgxuweCeAsUtaZ5ZXwyNz7',
  14: 'QmTmNqSk14gwU5bR4N6suJngTEfZQpJR8yq5DBbuhynSjk',
  15: 'QmSuXBBAFFTMbQBwZwUjfVNLQ1PapxhFHDV9oCUpWPcnrL',
  16: 'QmcD1V38yQNFV7F59GQ8Mr82WeWxtySVDz6d4m5N8DqcNv',
  17: 'QmRg8fGKKKeSGfkPogJS5YNMqff8WZY1x3QfqxbgcjVQGL',
  18: 'QmVrGLhhVswinGbN8K5BEu9FbpEMY7X2T63Ux7idJ9N1Ci',
  19: 'QmaRKHyEn8hRcfudJMEfZGuvca8SsNTs8gReFynLVHZxf8',
  20: 'QmQ7mJ5dc1SnJAgnPJwM17nSLbexHugrw5UagvXXk8LWam',
  21: 'QmPfYPP7zjMnozSFohEN575nxtJKB8rNNEDuV4pVPULat6',
  22: 'QmdyFf15em6sEC22nrG5MhTb1JfJydw1pYLGygxm7NPFMM',
  23: 'QmSXifySnPnu6puwPE9SCzVqpDZAfc8TqKPcmv1hPn94sk',
  24: 'QmP67VWk7qpsTuzC9EMWmhLMfEfysQUMEQ8k2ym7EVaRXS',
  25: 'QmXVPdJVN1tBzw9nEKKKgKG5GkvYtWkXo7fiim63TFK8Ry',
  26: 'Qmaaxi7LxisVmnQX2TP5rAH7pF4nD1RpD4Zeb3Jiy6tQys',
  27: 'QmRtXGg3uyCofLJQHymWM3xPPEJZr7BhSRSn3EK7zz7ynJ',
  28: 'QmerzfkLey16PxB1LmZMn156zfF4d8e4JQbdynuNJxeqpZ',
  29: 'QmZ9rmonJ2qyULvED3nzXHMqWhJ1CaCSRv4TTBreuVisCR',
  30: 'Qmb5ok4Fwj13XcRnGSDZPEtvWpPtiAP7kSPSvNXfjhV931',
  31: 'QmR6Mm1VmjbhnXrwxvx5f9EBJcoSjUrAFvoDRu5T26XGiu',
  32: 'QmWawygMSDCLrCzbTd5yTo3ouSzRiFQ5jfwSt5iQcsXohn',
  33: 'QmVfWkKaV4rL9Q3RBSYBwc3mGEAtG1QvWJ15etGnsixUBa',
  34: 'QmWjdwog9RLtauzyGjrtU1yVEeePNDWTtA48JnoRDFDace',
  35: 'QmcC4KHgtw8WGVEgfr8C6sz8sbMcsqPvnRynZnTvBUDTCA',
  36: 'QmRPR7Ba3gkDUK2qDZr3oYwNXd2SoqD9kXjY5fnRpgA6Vf',
  37: 'QmQNcY8ct2T6Mg3LQmSumKQdMHprJu1PGmQdqLX6XFjTY7',
  38: 'QmbXnEeBQiyrwqt9Nonss74qjMWSqFmz5QuukfyR68z6Wu',
  39: 'QmTnSDBSgbWecweTrLgBYXSMsiwHR8ZZSqtwzsxTpMczWY',
  40: 'QmS1VtrTys3psYVxfHGtU8scr2djFfekTzKC3q3UNTsn9C',
  41: 'QmYJ7kNRCyGgdzhBfQmBrjrPLAERs3kfEg2cYpUoRcrCpa',
  42: 'QmNsc7NUogncwJE1UBK2JZjfBtwkV3eU8t37nYjnefYGHs',
  43: 'QmaDvcz3uutuTpmUUkREwrZgwyLKYoonSgyZ2WjNgouLWG',
  44: 'QmRbq8KKhChTfVKTsRVxH5xHakRcijWkPUJvjYJt5Zwxkb',
  45: 'QmafvoAVkM5pcC4DzjHzm7ePHBJYVSeRdyi2jpk41CdLmp',
  46: 'QmQxxCKBhFMdKz4S5mbucEvtFADqi1j4av454J5ZQDYfvF',
  47: 'Qmbo96hY9cPhv12eNALLjnGnsjL5Miazbtqx9py52qZvDH',
  48: 'QmaxN5eidJysDrtcySrrwGEVKfGRspHUxRauDDfexuGsuK',
  49: 'QmWYd8X7MowwQyWZSwYZ16pN6FDuAHRxGbx2CtrnoFDEsn',
  50: 'QmagTDjbjUoQXmEQYEfZHBGSuqAaYWZN32DT4m8wETGZZy',
  51: 'QmRmCj4UqeUvGzopYibXgXP8AyDwP97KEAGaVEzBLHG5pJ',
  52: 'QmbnfRsK2giVDEsYgC7w8gQmkhvAcqFtgFr72niXuvURua',
  53: 'QmZBgKPn6DgyhjZa6MJzK64PrUYL9PLhJ9eHVmdrQQTp4g',
  54: 'QmSjyZhTUokSKvKPDKk6MwGgAK3LEoJ7rLttkKwXqmW7b3',
  55: 'QmV1NbVPVdEWz5ccHsEURsnF3MW1JQUMBktPBX8M8nwk5J',
  56: 'QmbjHSQjNSpLrqt9nM2Y5y5Dr6MmqKHQ8ULUC9f5xtvzck',
  57: 'QmfWSPcVhAyn5oXBy4vRQUmg7QC1UcNbwbRi6RfxHofFNU',
  58: 'QmfJT7JJJE2grn3yAQFhz5vCisEERfFnQuXLRKpoP6w3Ph',
  59: 'QmRTRk7wdaRfiAA7JxVNGShwWERD9RuYWrJXbeAPHxCRYq',
  60: 'QmPUk3Tc1CXhEkWnnVjW7W9G9rhpcACnJFsJ2vumZFugpj',
  61: 'QmZ2nSr4P52pUAzF1dcyAbD7an2fTjyzWBZJvKUNoY7Uxg',
  62: 'QmYCK7KN4u7NgzoihRQ6cY4Ez5T15iswZJ9JXFYWwK7NdK',
  63: 'QmNsPEhhFR2MUW6fJAZUBtJ2ETPYpj47xx22ZcFH2vKfQi',
  64: 'Qme21mAynyq9UmSMdwjaYTqVCYAuBKdP7KaEwu5eF5xAmj',
  65: 'QmViNEUapaZytuLmDpn1orYpL4i29eTdnr8AEWtakDSSrF',
  66: 'QmarPLVUXxMuoPu6jCF7jnCopTSr1TvLQH5n6RST9HwrzR',
  67: 'QmbNRxCv5D1tDeFwbb1oBKGR9VBcpSCGe2N6tiYAoyobib',
  68: 'QmTwpvBtg4QEJ7qCrnAy84p3Ugx3cFWFpmCgJW8nZSSDRQ',
  69: 'QmWy8hkKKnumAe7g7Ybq7TvM8cKs7vsLaQCMb5RUwb7yUR',
  70: 'QmWd2T3tZiDHhW1KxYzTQRyoAaPnQZNKpmutiw2GH1N8gp',
  71: 'QmQPzwTyaQ7d9yW5MuJQhQjLo313atpLBs1ojxqrTRxKFm',
  72: 'QmVLg4zYeG7R6uxTkwciVmjk7P8MR4CrUtdU59oooyQvyi',
  73: 'QmQ9NjFFnKwJczb48xi3zGCZ7s995mKPqeGGEarCuEvHdJ',
  74: 'QmPxRfk3srVvXqYrbaUTTfVEeLEBp6fWwZ5M48MTm471aF',
  75: 'QmV1Vf5JjP34pPbsPhSWCFKsU41QsREjgJESd7Pzu5ZJWt',
  76: 'QmQehZ6ChtFoFobWmN9LHFzpGpX8rVKE6sf8tyTdrxUzc4',
  77: 'QmTBJR3hppxd8GrYspXmg217cwxJDvrAf1q4BXKhqaMwhk',
  78: 'QmfWZWyDVtxZDXQEYZirVce9tKRUup3hZjGGyY7WHb2uTj',
  79: 'QmevPn6y9ypabxuYvmui1ZCyTfWc3BGetbKPs8NwNFNP1N',
  80: 'QmfUwsXBt5umeM2eGPvr5UwUVUN6cw7RRGotZAZpyj4rB6',
  81: 'QmZ4rmFotSYA1nyuZEsQEtQaNT7AQeC3t1QNYsTM2fTdjh',
  82: 'QmfZNbpbtBa3LG1Jcu9DSGCeoMFGQGcPTrAUTCVBTW1gB9',
  83: 'QmRBzYVCnmKnbDedsDCdFwbLZ2uhsi6P8QcT5Dqn53JWLj',
  84: 'QmRCuVpsktjGfHAkJ3HoHWz7vm8Dg45KX9MSXSvg8xHxP1',
  85: 'QmT25dJkzH81Ep8GM6gKgcUumHjZBA6SaFNed89qVVvz8B',
  86: 'QmQkMqWrZRrYAJzVbo5LyLA4qe6hnYTxaw5uiYFtRmYHUm',
  87: 'QmYixWmQfSY2CrbaEbnQ6NDdfWNCw8YzAZukRrd7jEcdZc',
  88: 'QmbyPP4b31tX4MEXWbAyzrch7as48KUwMDEUgRNdidZ4f2',
  89: 'QmZUeBYFEipMnevrQbx2v3JfmdYDow8gwTj2bhqzhzGamq',
  90: 'QmP3J9mX1NXJ6BPs7kShhDy1QySTqcSMmzAfaMTKa7Y6kY',
  91: 'QmQSPS41ffdvuhPFy6N99BokVPYGzKzXkvZT5HEBHNGYXB',
  92: 'QmNoC2W9QdsGqweiRFvgj1GDP2x3gBnje4BosjWp28EEjV',
  93: 'QmXDaaUEnK9DKtwJLNvizpjryaR1yBsPMsX9e3NdwWcv3L',
  94: 'QmduxTUnF9uLsfv1tgun1XQL4DWdfp2L9omfatQ8J6Qw6x',
  95: 'QmWo1USU2sZHhDADue9wMw169zqQDu7v1qd3EjQDvsedT8',
  96: 'QmW8DhLtiiTGfDkxKxTjChJwdrwQNaPSMQoo7EbgtR22sU',
  97: 'QmYDwHvtpXiX1NrXpLxjmNSAGJKsSxhrioysqFLV1UuBjy',
  98: 'Qma8zR3UPEVqTyDSCecZuyKeGKaJZpR4QYzE8cPg8dCD4V',
  99: 'QmaD9MbTTJfDyPCsfLTwesXstgYnYvYXaQhUMnc2hBrzEb',
  100: 'QmU9UZYFmyz9w2gErLsefFG3MaUuKhiBXhdnYVCDFiLFGo',
  101: 'QmcDYFEWfa1iRVu1ZRdmvbiRwrusasMs5SZ6NXDobTzBaj',
  102: 'QmbgS8nz9msqjmut4YbT719azMEQ8msz5TvEtfe1fKhb4i',
  103: 'QmYKERjRBiJLbRRhKVjBvvVYH3ZtJpoCgBAy92k3tDSr51',
  104: 'QmX9CZHwK6fbwAJ88J8xkfcFp6JqVuDFbsgg5E8pfnuzQL',
  105: 'QmaR7Ac8WLzm95EUqBLD6ozdqZqAXdTUMSizuT57wyxkDY',
  106: 'Qmc3rx2yNuq8oBDwNgtKRt8iC2s8Lc2goPjroBiBUQjBNJ',
  107: 'QmTf6Z4dD8kK4xPsw9fcfFwrsdSTB1uWjyqR1bZeZJbmjZ',
  108: 'QmfL9JKv4pgHut3nEQ8YvT9HJ13m2MHtVLQPVhzdHsUALu',
  109: 'QmQ2S8rjf97kuvUfRejLeom5ixhNbXnBqcrW3yqK5nyAEN',
  110: 'QmZB1tXotEDtJwLN61zixqHz7XFfegViwaCVnryLvSxSYN',
  111: 'QmSbZCrQ9w4WEMAmJfAxe8mXdRgxRmaXampUjPR1XE6uvU',
  112: 'QmaaigiJu3Qzs7F4TQ9uNhspj6GstfG79XoC4CwjD6Vx35',
  113: 'QmQrHM5n3g43mPTCAPVRxJ7hzLchday47gp53QANGwqYwL',
  114: 'QmahnzV7ZFz9UTeTZKxu8R6RK8dyCNVNtCG4eQYCoTeUFQ',
  115: 'QmRkDZaZBL6pTrrAGBLVFWddL7Pde1fN3JNGrkcSVqBbAt',
  116: 'QmPzJ5VnBs9sDFDwBrgkKEjaDKRMsUYPUbrcQHXK52Dy4R',
  117: 'QmPXVLWVc68ZcYwJMK7KvXGxgBvcoxjtA2QVtxaGHAU8jx',
  118: 'Qmea84JoE3YFsN24asRYXRzi8KVDT7NCcGQqVwgeeh16k6',
  119: 'QmdLMaY4VSSCLtd51rQadLVC1QaHfd8dMHzdQuXkxy5G6Z',
  120: 'QmXNfY5J8TmxwobJCySr65dztjRpLEHYNGeu3kz5koLba3',
  121: 'QmcRuwmBcE4w8A4yQ7kzMUp7e8SmrGwGnm7TcCPdJz72xX',
  122: 'QmU6wxFC7VjNmiakPsu6Fkfb31KhbVo4uPWUPET2j5jQ9U',
  123: 'QmQ2QkpwN3AFRE9JJ5EkJEozkxQ99KJWPnYdqQEKucTGoh',
  124: 'QmXMjnodyDbYvYsxE1zeL6371brGy7z6qrstrNBfuUsk2m',
  125: 'QmbAojAi6ECM2bWW9sCTarY76SAz1S8jkUWnu5M43PAPo9',
  126: 'QmReSx9dBghzE68dqtDkTqBcpF3cfh2BDRb3tLKB3adRoT',
  127: 'Qma91ie6B4LYiSEx6tZD44izhv1wJtEBAypP4LprNnPJjx',
  128: 'QmQhdguZYMdDBKs4bYfV56A79rPUGzqRu3Eh9ATX7a9812',
  129: 'QmULjgzaXqj9HkG9aNaEzs4Wnn6ciwHsa13bqWjBCe8Wvu',
  130: 'QmcN4eD2bqf9Y5J8CwQDzSs2caDBjR9UXK5112mkFPctMk',
  131: 'QmUJUKGbVdWfvD6vyHE4eDbM395Fc3KTbtKxDucS3vbAMa',
  132: 'QmditPaFKPNe9uAzM41Mp8xo6S1QgwHi4pkQNnSnwyqPNS',
  133: 'QmRELchqfbh8oKHd5PVFKmkN1wYCBqzMzd7A8xtgHvaNwc',
  134: 'QmbrpgAF5fWLiUuNKfv8uYZjNp4Xhfdopf6vqqwBDRHvsf',
  135: 'QmZ1u6kAk9THEL8BKkpKmJkF8WtkvS69eYLrYdtNWsNhLJ',
  136: 'QmbWSjqZ6phx4d5uhEAqNE3Cw783DmrHLAhyzLvcW4oSSp',
  137: 'QmeyRomFbj5cUTGwFL95BzXAtcKVNBdDj9Dfezz2vjKVrg',
  138: 'QmXtW3xbbRtznZewxGgJAC2ReZn4k4p6YEL35xezTJ83KV',
  139: 'QmVWXdM8mKgU2ZrKHnVUE2uJDYhWbPxhnFVKTA8dYo3Dz9',
  140: 'QmPgMbAF8eHpX2gUXKZGE8HVPNHzzW7bRcPGDtmHaB3Abp',
  141: 'QmYq4oPuhtrwf814vvMXhpjx4GNamVebqQ1SoWzmSmmBtZ',
  142: 'Qmas11DWSPSgaR7LBqe1vWsGc4Ka2aDAzaxwH3Vo6o2n7D',
  143: 'QmQm4MnNboFdKLP5U7ne6Z6V9Rn3hnBBXsKjyy4M9XbrqT',
  144: 'QmY4JVr27FD5Zsd81SXyyGC33KJEpRA3Hu6p2wjr8PXBBP',
  145: 'QmZnCX2mdB6Mx2nyemN1NYNfnRAE2phdARfvu9dbQpCJmX',
  146: 'QmVHRJTZRkqnTLLVRT9U7zUgJ8RFXMgX3MCHJPp1yKX57T',
  147: 'QmbaHBYhBQvdTKMA6cDhv5GQLkePosXAiFD6UpBCHr9pvX',
  148: 'QmTV8Sb5G6CLWNscffhjmSsboLPEcR4oenYzF6sdLFT9FB',
  149: 'QmSqTjaDYcVg4nRpChnjSbShtfCL97dF7EDGRu7ou42gKp',
  150: 'QmV5H5h3ZVrg8yLQEDDovG7YR9s5fQ2LW5bvyUba48uS1B',
  151: 'QmYhqML67CcwpfoRcK3jsEjA6NXquYpdB2zwURe5tWpVvp',
  152: 'QmRxns3MumqpCaPDGGmKZPngDxE9eC957bEJhgozdSRBKY',
  153: 'QmXEYYra42siH52Y9yJB3WawFhsZPt2wY9An77BDX2n21z',
  154: 'QmWnnPqZXWANw5pYpCKNohq5QFsasFVtZzgtcKdK33xgs4',
  155: 'QmPY4tfTLcxNs5QfVYZ3HP4ViUgNrDMk81xqzXkyEp5cjv',
  156: 'QmYg9DHEThHyCcYntuAhFr6EPRZ6NxsfHDEdrUxSvfciJm',
  157: 'QmWSaiyTjGzdgCfXtTqnYcwttaYRGFwtBBvSQCycxZCF1B',
  158: 'QmNNUBArHjt5J3ois41tfXbCWWvbEhQU42z3DXnBwwasmF',
  159: 'QmcasVBLN2mxE4ZRPDB918GnvNHo7dcYen4DWhS6ZqiKjq',
  160: 'QmPABXj38XkYGvC8XYrjM4sLXGSZyi6ZyvqcVVVYQ4EwMQ',
  161: 'QmUBRuA2Haa4geWwCD3mzp6QC9fapUsHwSUTf88F6Scoxy',
  162: 'QmeKrZ3AkVLXmrrRXDkvkoHgYmq5JHMrKhq2mPgVaaLw63',
  163: 'QmYTHN7FSkzFFCcGbvSUBxfByEPV4ZvAsPi5cxwuQzA5am',
  164: 'QmNhzXnbrxxEhL6h1bEGyFePVfAXy4sphLgAxAns8VYNa8',
  165: 'QmUCJa86MgPV4yo35qUJP2sVpnd9TAMKf58WRY7t897z27',
  166: 'QmRZnTKvhCrVQPZnVhteC13jDW4AHe1z6fRQ2crVs3RvuK',
  167: 'QmYBEMV7XHv9nMMNLxFxbEbEQFNcKAq7w1kuQPwBEWb6fG',
  168: 'Qmbdiy2agsR4AbeYAnn6utJWA5BHZy4FMbHZuaLSS1cCcD',
  169: 'QmWrBca9UTgjnXbEioyzcuzN5NU5UZNE1tHBAfUg8Q87fm',
  170: 'QmeL9e6TwqYJYzm23btwQrouLYDnCaqLpJCYmnf3fUr4fd',
  171: 'QmS591ZkgVjiD7W3keqKaveBEFtfMsEASSC94gPwsanYdg',
  172: 'QmNyFb89cqvH7ZYg5JXGzy9K7UZTdypbRN2JmoVrm1yvmz',
  173: 'QmUFPJhWukGvW6arxwCtQ9TMas5L9AicSLhgyUfrHsxABt',
  174: 'QmfKMtTY55tZ7FXYUYetsXodUfJvMZwDZQ3oBiggNQYAzR',
  175: 'QmdLaLzh28sDQpCivzS5wX1X2UgGC9morA81VL9as2oD1D',
  176: 'QmcBAKUpfDuzT5Gw4s4YuznM2GS4aqDWREfzyRLiwm91oy',
  177: 'QmYo6d1tMeGLLsRPsB2DZYZZL3r4Z16LreD3i5tG759tAF',
  178: 'QmNvS2GC5p63u2GRzXAxQ4NkhYSTUnf1bYic42CmMGwqc6',
  179: 'QmSqN6yURhx6bbdY7fDSwDu2Pwr2QKfxoNpZMgDaMx9Vve',
  180: 'QmVwzhKWDDoqP8HJ3hzLmGvJDQYVMV33LQzWPU6yyDviPx',
  181: 'QmQueppamQFezCaqV6UvVijRBreyFpWfAwCrStUZxKGqNF',
  182: 'Qmcx2j96DMei9ZsN2xcJXmjhWYEoYFnm1JjRhp2ENapF2e',
  183: 'QmeY3TnFGeMyG4MytKAcC8iipmpoUScxz1p1pPph1AudoE',
  184: 'QmSCQqpt3d4GjUMUDJwXrfugVMT1gcpKcKeN4y9ooyRQg7',
  185: 'QmdzS6oo11qpycSUR6t12enyeeP4FMdKGc9Tacwgknxmf1',
  186: 'QmcmCuU4wgvUVbSpq8ZHSGuHayvSzwL2bsYVSrpwXNgsLS',
  187: 'Qmb1VszAZ4vE3p1Yzgrp2qRVVrdgXwfyQRDaZfEf99ewvw',
  188: 'QmZmqWAY83HQekc4pfimwLgSSgw2sYmuXQZkmj9adPzzvj',
  189: 'QmWaH6hAdVsuiZFmHjhKFBy569y4NMntXJNAXR2ZdLZt6T',
  190: 'QmPvTfaXj3MxPhAiMUWGtQysCLyE8bZzDxkhVfm5ZYPEPn',
  191: 'QmWXWhaRtcDBQjmbR3SQJegmBqtS7NoQoVASmh4kHYMGLi',
  192: 'QmeWhVRUF2HKjQSMbLxVUQJgpQXs3AEuke39Zdsfuy5HeA',
  193: 'Qmaqm2xkLYkdkRQR6hHorLZqNUNcxjwHbAVhnhznzccsBq',
  194: 'QmYf6DV1hMsr8x5SY5zZQyuvsT4q2rpqYtRf5hPHT7NrTC',
  195: 'QmVhMB1EouXLcM1kWZq8A1NrsXcfsDARe7Zd3MydF8s3Gp',
  196: 'QmV9JjixYFeeCFjynm3eZrk2cenFokqTqbLbJT788qspCy',
  197: 'QmNUiTDo8MoRFrkjUYffhKc9mwkcYa8AE57MDb9braFgqW',
  198: 'QmZnHhs2xC2skn61Qs2QMiw5oigczUTjyVzkzezb5x7os8',
  199: 'QmQ48Ag9NRrvq5py5i5FxsNxYkefRzi4YETb5GheAgQNv7',
  200: 'QmNaWzHcJS1KboK5vcTm4PxxL9MY5hNiTQzxJR85z2zdKk',
};

export const FLIP_MSG = 'FLIP';
export const WITHDRAW_MSG = 'WITHDRAW';
export const MILLISECONDS_72_HOURS = 259200000;
export const MILLISECONDS_24_HOURS = 86400000;
