name: Publish DockerHub

on:
  push:
    tags:
      - '*v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Version info
        id: version_info
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Build and push starkfinance-launchpad-api
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: code4futu/starkfinance-launchpad-api:latest, code4futu/starkfinance-launchpad-api:${{ steps.version_info.outputs.SOURCE_TAG }}
          github-token: ${{ secrets.GIT_AUTH_TOKEN }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GIT_AUTH_TOKEN }}
